#!/bin/bash

./run.sh com.typesafe.play:play-java-jpa_2.11 2.5.1 
./run.sh org.jboss.forge.furnace:furnace-manager 2.0.0.Beta1 
./run.sh com.cedarsoft.commons:inject 6.1.1 
./run.sh org.apache.cxf:cxf-bundle-jaxrs 2.3.3 
./run.sh org.tinygroup:org.tinygroup.exceptionhandler 3.1.0 
./run.sh org.ops4j.pax.web:pax-web-spi 6.0.5 
./run.sh org.codehaus.sonar:sonar-batch 4.2 
./run.sh org.kie.server:kie-server-rest-dmn 7.0.0.Beta8 
./run.sh net.thucydides.easyb:thucydides-easyb-plugin 0.9.77 
./run.sh io.fabric8.forge:kubernetes 2.2.32 
./run.sh org.codelibs:elasticsearch-dataformat 0.1.0 
./run.sh cd.go.plugin:go-plugin-api-experimental 16.7.0-3815 
./run.sh org.fusesource.fabric.fab.tests:fab-sample-camel-blueprint-share 7.1.0.fuse-047 
./run.sh org.jbehave:jbehave-weld 3.5.4 
./run.sh io.fabric8.devops.apps:keycloak 2.2.23.10 
./run.sh org.apache.karaf.management.mbeans:org.apache.karaf.management.mbeans.log 2.2.10 
./run.sh org.wicketstuff:input-events-parent 7.0.0-M4 
./run.sh org.ow2.jonas:jonas-genic 5.2.0-RC1 
./run.sh com.google.apis:google-api-services-adsensehost v4.1-rev142-1.18.0-rc 
./run.sh org.jbpm:jbpm-flow 6.5.0.Beta1 
./run.sh org.drools:drools-wb-guided-dtree-editor-client 6.2.0.Final 
./run.sh org.eclipse.xsd:org.eclipse.xsd 2.10.0 
./run.sh com.twitter:finagle-test_2.11 6.30.0 
./run.sh org.webjars.bower:angular-datetime 3.2.2 
./run.sh org.typelevel:cats-macros_2.11 0.6.0 

./run.sh org.bekwam:tscriptrules 2.3.0 
./run.sh org.apache.cxf:cxf-tools-corba 3.1.1
./run.sh org.xwiki.commons:xwiki-commons-xml 7.4.6 
./run.sh org.jasig.portal:uportal-db 4.1.0-M1
./run.sh org.infinispan:infinispan-tree 7.2.0.Alpha1 
./run.sh com.github.vatbub:common 0.0.23 
./run.sh org.ow2.jasmine.kerneos:kerneos-core-server 1.2.1-M2
./run.sh com.lihaoyi:ammonite-compiler_2.11.11 1.0.0-RC8 
./run.sh org.specrunner:specrunner 1.3.5 
./run.sh org.mechio:org.mechio.impl.motion.dynamixel 1.0.3 
./run.sh org.ow2.orchestra:orchestra-packages 4.2.0
./run.sh org.drools:spring-camel-drools-decision-table-example 6.1.0.Beta1 
./run.sh com.github.cafdataprocessing:worker-policy-boilerplate-worker-handler 1.4.0-60
./run.sh org.commonjava.maven.ext:pom-manipulation-ext 0.5 
./run.sh com.nepxion:aquarius-common-zookeeper 1.0.2 
./run.sh org.json4s:json4s_2.9.1 3.2.7 
./run.sh org.kie.server:kie-server-rest-jbpm 6.4.0.Beta1 
./run.sh org.swinglabs:swingx-beaninfo 1.6.2-2 
./run.sh org.dihedron.activities:activities-core 0.0.3 
./run.sh org.mobicents.smsc:mproc-api 7.3.115
./run.sh com.fizzed:blaze-groovy 0.6.1 
./run.sh org.mobicents.examples:mgcp-demo-ivr-sbb 2.8.26 
./run.sh com.github.chrisbanes.actionbarpulltorefresh:extra-abc 0.9.1
./run.sh org.eclipse.rdf4j:rdf4j-rio-datatypes 2.1.2 
./run.sh com.graphaware.neo4j:tests 2.1.3.10 
./run.sh com.amazonaws:aws-java-sdk-kms 1.10.46
./run.sh org.glassfish.packager:metro 3.0-b49
./run.sh com.mysema.querydsl:querydsl-core 0.3.1 
./run.sh org.jvnet.hyperjaxb3:hyperjaxb3 0.6.2 
./run.sh com.microsoft.azure.sdk.iot:iot-device-client 1.1.26
./run.sh com.gitblit.fathom:fathom-security 0.7.0
./run.sh io.apiman:apiman-test-policies 1.2.6.Final
./run.sh com.googlecode.gwt-test-utils:gwt-test-utils-gxt2 0.39
./run.sh org.mobicents.resources:restcomm-slee-ra-map-ratype 8.0.19
./run.sh org.codehaus.openxma:dsl-core 5.0.7 
./run.sh org.glassfish:osgi-ejb-container 3.1-b12
./run.sh org.elasticsearch.client:sniffer 5.0.0-alpha6 
./run.sh org.kitesdk:kite-data-hive 1.0.0-cdh5.4.5 
./run.sh org.codehaus.cargo:cargo-core-container-jonas 1.4.6 
./run.sh com.sun.xml.ws:jaxws-ri 2.2.11-b140518.1731 
./run.sh org.glassfish.extras:grizzly-container 3.0-b72
./run.sh org.srplib:srp-conversion 0.5.0 
./run.sh org.mobicents.servers.jainslee.core:spi 2.8.114 
./run.sh org.apache.hadoop:hadoop-mapreduce-client-core 2.0.0-cdh4.1.2 
./run.sh com.ibm.websphere.appserver.spi:com.ibm.websphere.appserver.spi.timedOperations 1.0.17
./run.sh org.jboss.ws.native:jbossws-native-jaxrpc 3.1.2.CR2 
./run.sh com.h2database:h2 1.0.64
./run.sh org.codehaus.sonar.plugins:sonar-l10n-en-plugin 3.4 
./run.sh com.google.apis:google-api-services-content v2-rev29-1.17.0-rc
./run.sh org.eclipse.jetty:jetty-deploy 7.6.17.v20150415 
./run.sh net.wetheinter:xapi-core-api 0.4
./run.sh javax.xml.ws:jaxws-api 2.2.3-promoted-b01 
./run.sh org.jasig.cas:cas-server-integration-memcached 4.1.0-RC2
./run.sh org.onosproject:onos-features 1.6.0-rc1 
./run.sh com.aol.microservices:micro-client 0.65 
./run.sh org.sonatype.nexus.plugins:nexus-restlet1x-testsupport-plugin 2.6.4-02
./run.sh com.gitblit.fathom:fathom-test-tools 0.6.1
./run.sh org.digidoc4j.dss:dss-xades 5.1.d4j.3 
./run.sh org.apache.servicemix:servicemix-saxon 3.2.2
./run.sh com.amazonaws:aws-java-sdk-elasticloadbalancingv2 1.11.110
./run.sh com.brettonw:bag 5.4.0
./run.sh org.eclipse.aether:aether-api 0.9.0.M3
./run.sh com.redhat.lightblue.rest:lightblue-rest-auth 2.16.0
./run.sh org.wildfly.swarm:camel-cxf 2017.2.0
./run.sh org.sonatype.sisu:sisu-guava 0.11.1 
./run.sh br.com.objectos:schema 0.1.1
./run.sh org.jboss.windup.rules.apps:windup-rules-java-project-tests 2.7.0.Final 
./run.sh org.e-hoffman.build:StaticAnalysisConf 1.0.3
./run.sh org.rhq:rhq-core-plugin-test-util 4.11.0
./run.sh org.scalaz:scalaz-core_2.9.3 7.1.0-M2 
./run.sh software.amazon.awssdk:codegen 2.0.0-preview-5
./run.sh org.wso2.siddhi:siddhi-query-api 4.1.5
./run.sh org.jboss.forge.addon:core-tests 2.12.3.Final 
./run.sh io.airlift:dbpool 0.98
./run.sh org.apache.sling:org.apache.sling.scripting.jsp 2.0.3-incubator-R702729 
./run.sh org.mock-server:mockserver-netty 3.10.2 
./run.sh net.ripe.rpki:rpki-commons 1.0.24 
./run.sh org.wildfly.swarm:container-test 1.0.0.Alpha6 
./run.sh org.scalaz.stream:scalaz-stream_2.10 0.7.2
./run.sh org.easytesting:fest-assertion-generator 1.1
./run.sh net.liftweb:lift-record_2.7.7 2.1 
./run.sh net.officefloor.tutorial:SecureLinkHttpServer 2.8.0 
./run.sh com.sun.enterprise:config-types 1.0.60
./run.sh org.openrdf.sesame:sesame-testsuites 2.8.11 
./run.sh com.epam.jdi:jdi-uitest-core 1.1.3
./run.sh org.chtijbug.drools:guvnor-api 5.6.2.chtijbug 
./run.sh org.wicketstuff:gmap2 1.4.15
./run.sh org.apache.tomee:openejb-itests-interceptor-beans 7.0.0-M2
./run.sh org.kill-bill.billing:killbill-oss-parent 0.7.7 
./run.sh org.atmosphere:vibe-platform-bridge-jwa1 3.0.0-Alpha9 
./run.sh org.jbpm:jbpm-executor-ejb 6.4.0.Beta2
./run.sh org.apache.activemq:artemis-core-client 1.1.0.wildfly-010 
./run.sh org.webjars.npm:babel-standalone 6.24.0 
./run.sh io.fabric8.archetypes:archetypes 2.2.164
./run.sh io.nats:jnats 0.5.2 
./run.sh org.apache.servicemix.nmr:parent 1.6.0.redhat-610043
./run.sh de.sciss:scalacolliderugens-plugins_2.12 1.16.4 
./run.sh com.google.apis:google-api-services-bigquery v2-rev84-1.13.2-beta 
./run.sh org.tinygroup:org.tinygroup.cepcore 3.4.1 
./run.sh org.apache.hbase:hbase-prefix-tree 0.98.5-hadoop1 
./run.sh org.realityforge.arez:arez-processor 0.49 
./run.sh com.twitter:finagle-base-http_2.12 6.45.0 
./run.sh com.github.kristofa:brave-tracefilters 3.2.0
./run.sh org.glassfish.jersey.connectors:jersey-jetty-connector 2.5.1
./run.sh com.amazonaws:aws-java-sdk-cloudfront 1.11.160
./run.sh io.norberg:rut 0.7
./run.sh com.carlosbecker:parent 1.5 
./run.sh org.onosproject:onlab-misc 1.5.0-rc2
./run.sh com.lihaoyi:ammonite-repl_2.12.3 1.0.1-1-d2e04ce
./run.sh org.wildfly.core:wildfly-core-security-api 2.0.0.CR7
./run.sh org.glassfish.metro:metro-cm-api 2.1-b22
./run.sh org.apache.spark:spark-test-tags_2.10 1.6.2 
./run.sh com.foursquare:spindle-runtime_2.9.2 1.4.2
./run.sh com.episode6.hackit.mockspresso:mockspresso-mockito-powermock 0.0.5 
./run.sh org.commonjava.maven.ext:pom-manipulation-ext 0.8.1 
./run.sh org.apache.cxf:cxf-distribution-manifest 3.1.0
./run.sh org.metawidget.modules.commons:metawidget-beanutils 3.9 
./run.sh com.cocosw.accessory:views 0.6
./run.sh org.apache.wink.example:apps 0.1-incubating 
./run.sh com.sun.jersey.contribs.bill-burke-book:ex06_2 1.4-ea06 
./run.sh com.github.dziga:orest 0.1
./run.sh org.bitbucket.bradleysmithllc.etlunit:etlunit-maven 2.0.15
./run.sh org.xwiki.commons:xwiki-commons-xml 5.4-rc-1
./run.sh com.facebook.jcommon:util 0.1.14
./run.sh com.amazonaws:aws-java-sdk-sns 1.11.230 
./run.sh it.lucichkevin:cip-library 0.4.1
./run.sh org.apache.calcite:calcite-avatica 0.9.1-incubating 
./run.sh org.codehaus.janino:janino 3.0.4
./run.sh com.holdenkarau:spark-testing-base_2.11 1.4.1_0.2.1 
./run.sh org.apache.hadoop:hadoop-minicluster 2.0.0-mr1-cdh4.5.0.1 
./run.sh org.kaazing:k3po.driver 4.0.0 
./run.sh org.codehaus.cargo:cargo-core-container-orion 1.6.4 
./run.sh io.fabric8.forge:camel 2.2.113
./run.sh com.payneteasy.superfly:superfly-common 1.2-10
./run.sh org.apache.karaf.webconsole:org.apache.karaf.webconsole.gogo 2.3.0.redhat-610009
./run.sh net.liftweb:lift-archetype-blank_2.8.0 2.2-RC5
./run.sh org.apereo.cas:cas-server-support-saml-idp 5.0.3
./run.sh org.kuali.db.impex:torque-generator 1.1.3 
./run.sh org.fcrepo:fcrepo-transform 4.0.0-beta-03 
./run.sh org.apache.cxf:cxf-rt-databinding-sdo 3.0.0-milestone2
./run.sh net.bluemix:bluemix-cloud-connectors 0.0.1.RC4
./run.sh org.apache.sentry:sentry-core-common 1.3.0-cdh5.1.5 
./run.sh com.thoughtworks.inproctester:inproctester-project 1.0.12 
./run.sh org.jboss.resteasy:resteasy-jaxrs 3.1.0.Beta2 
./run.sh com.github.signed.inmemory.jms:jms-server 0.0.3 
./run.sh org.neo4j:neo4j-io 3.0.0-M03
./run.sh org.datanucleus:datanucleus-rdbms 3.0.8 
./run.sh com.badlogicgames.gdx:gdx-controllers-parent 1.6.3
./run.sh com.bazaarvoice.bvandroidsdk:common 4.0.4 
./run.sh org.pustefixframework:pustefix-samplebank 0.19.30 
./run.sh net.sourceforge.pldoc:pldoc-cpd 0.1.8 
./run.sh com.alibaba:simpleimage 1.2.0 
./run.sh org.jodd:jodd-upload 3.6.8
./run.sh org.pustefixframework.editor:pustefix-editor 0.19.8 
./run.sh uk.ac.open.kmi.iserve:iserve-swagger 2.0.0
./run.sh com.typesafe.play:twirl-compiler_2.10 1.0.3 
./run.sh org.pircbotx:pircbotx 2.0.1 
./run.sh com.netflix.genie:genie-client 0.20 
./run.sh org.assertj:assertj-swing-junit 3.8.0 
./run.sh io.getstream.client:stream-repo-apache 0.1-RC1
./run.sh org.glassfish.grizzly:grizzly-http-servlet 2.3.24 
./run.sh com.amazonaws:aws-java-sdk-pinpoint 1.11.197
./run.sh io.fabric8:kubernetes-api 2.2.216 
./run.sh io.crnk:crnk-spring 1.0.20170626133151
./run.sh org.springframework.data.build:spring-data-parent 1.0.4.RELEASE 
./run.sh de.deepamehta:deepamehta-accesscontrol 4.8.7
./run.sh com.isotrol.impe3:impe3 3.1.0 
./run.sh org.apache.aries.jpa:org.apache.aries.jpa.container.advanced.itest.bu
ndle 1.0.1.redhat-610033 
./run.sh com.github.liuguangqiang.asyncokhttp:library 0.0.1
./run.sh com.groupbyinc:common-http 34 
./run.sh org.glassfish.hk2:hk2-config 2.5.0-b09
./run.sh uk.co.jemos.podam:podam 2.3.9.RELEASE 
./run.sh com.inexas:util 0.1.0 
./run.sh org.apache.knox:gateway-i18n 0.5.0.3.0.1.0-1
./run.sh com.peterphi.std.guice:stdlib-guice-common 9.4.6
./run.sh com.twitter:util-thrift_2.11 6.41.0 
./run.sh org.apache.camel:camel-test-spring3 2.14.3
./run.sh com.atlassian.pom:base-pom 3.0.82 
./run.sh com.github.edgarespina:mwa-logging 0.1.4
./run.sh org.drools:drools-persistence-jpa 7.0.0.CR3 
./run.sh com.vladsch.flexmark:flexmark-ext-superscript 0.13.3
./run.sh net.anotheria:moskito-inspect-standalone 2.5.6
./run.sh org.codehaus.staxmate:staxmate 1.1
./run.sh com.amazonaws:aws-java-sdk 1.11.147 
./run.sh org.apache.tomcat.extras:tomcat-extras-juli 7.0.81
./run.sh org.xwiki.commons:xwiki-commons-tool-enforcer-dependencies 4.4-rc-1 
./run.sh com.github.artyomcool:retrace 1.1.1 
./run.sh com.github.lodsve:lodsve-core 2.5.4 
./run.sh org.glassfish.packager:glassfish-web-incorporation 3.2-b01
./run.sh com.dynatrace.tools:android 7.0.10.1010 
./run.sh org.camunda.bpm:camunda-engine 7.1.0-Final
./run.sh org.mule.tests:mule-tests 3.2.0-M1
./run.sh org.languagetool:language-de 2.8
./run.sh org.codehaus.cargo:tomcatcontext-war 0.9.1
./run.sh org.wso2.carbon.devicemgt:org.wso2.carbon.device.mgt.extensions.push.notification.provider.xmpp 3.0.179 
./run.sh com.badlogicgames.gdx:gdx-bullet-platform 1.1.0 
./run.sh org.apache.servicemix.activemq:org.apache.servicemix.activemq.camel 6.1.3 
./run.sh io.fabric8.devops.apps:keycloak 2.2.308 
./run.sh io.joynr.examples:location-tester 0.21.2
./run.sh org.jboss.arquillian.protocol:arquillian-protocol-jmx 1.1.2.Final-wildfly-1 
./run.sh org.wso2.carbon.analytics:org.wso2.carbon.status.dashboard.web 2.0.160
./run.sh com.ning.billing:killbill-beatrix 0.1.32
./run.sh org.jvnet.hudson.main:cli 1.305 
./run.sh org.zeroturnaround:javarebel-aspectj-plugin 2.0.2 
./run.sh org.springframework.data:spring-data-mongodb-log4j 1.6.0.M1 
./run.sh org.mule.transports:mule-transport-http 2.2.1 
./run.sh org.jbehave.web:jbehave-web-io 3.5.3
./run.sh org.neo4j.procedure:apoc 3.0.8.4
./run.sh com.agilejava.docbkx:docbkx-quickstart-archetype 2.0.13 
./run.sh org.springframework.integration:spring-integration-ip 3.0.5.RELEASE 
./run.sh com.sun.jersey.samples:helloworld 1.11-b02
./run.sh org.apache.felix:org.apache.felix.scr.ant 1.6.0 
./run.sh com.google.apis:google-api-services-storage v1beta1-rev123-1.21.0 
./run.sh com.google.inject.extensions:guice-jndi 3.0-rc2 
./run.sh org.apache.felix.karaf:karaf 1.2.0
./run.sh org.apache.kylin:kylin-server 2.1.0 
./run.sh org.kill-bill.billing:killbill 0.18.7 
./run.sh org.jboss.weld.examples.jsf:weld-jsf-numberguess 2.2.12.Final 
./run.sh org.codehaus.service-conduit:sca4j-rs 0.9.9 
./run.sh com.marklogic:marklogic-jena 3.0.2
./run.sh org.apache.geronimo.gshell.support:gshell-plexus 1.0-alpha-2
./run.sh com.pojosontheweb:woko-core 2.1-beta8 
./run.sh net.sourceforge.pmd:pmd-xml 5.4.4 
./run.sh org.ocpsoft.rewrite.showcase:rewrite-showcase-composite-query 2.0.0.Final 
./run.sh io.fabric8:wiki 2.1.1 
./run.sh com.amazonaws:aws-java-sdk-appstream 1.11.158 
./run.sh com.sun.enterprise.auto-depends-test:test-config 0.3.84 
./run.sh com.googlecode.sli4j:sli4j-log4j 2.0
./run.sh org.drools:org.drools.eclipse 5.3.0.Beta1 
./run.sh org.kuali.rice:rice-core-service 2.5.15 
./run.sh io.fabric8.insight:insight-log 1.1.0.CR5
./run.sh com.smith9.geiger:geiger-client 1.4.4 
./run.sh br.gov.frameworkdemoiselle:demoiselle-jdbc 2.5.0-RC1
./run.sh org.robospock:robospock 1.0.1 
./run.sh org.eclipse.jetty:jetty-webapp 9.1.0.v20131115
./run.sh com.visenze:visearch-java-sdk 1.0.0 
./run.sh org.jboss.jbossts.jts:narayana-jts-all 4.17.33.Final
./run.sh fr.matthieu-vergne:collection 1.4 
./run.sh org.webjars.npm:form-data 2.0.0 
./run.sh org.scalaz:scalaz-geo_2.9.0 6.0.RC1 
./run.sh org.infinispan:infinispan-commons-test 9.1.4.Final
./run.sh org.kuali.rice:rice-krms 2.3.0
./run.sh com.sun.jersey.contribs.bill-burke-book:ex04_3 1.2
./run.sh org.eobjects.datacleaner:DataCleaner-engine-utils 6.0.0 
./run.sh org.xwiki.commons:xwiki-commons-diff-display 5.2.1
./run.sh org.glassfish.jersey.containers:jersey-container-servlet 2.6
./run.sh org.glassfish.common:btrace-jars 3.1-b06
./run.sh org.apache.geronimo.samples:DataCDInfo-JTA-jetty 2.1.7
./run.sh com.sun.enterprise.auto-depends-test:test-inhabitant-generator 1.0.70 
./run.sh org.keycloak:keycloak-server-spi 1.9.2.Final

